module.exports = {
    ROOM_STATUS_NORMAL:"ROOM_STATUS_NORMAL",//房间正常
    ROOM_STATUS_DISMISS:"ROOM_STATUS_DISMISS", // 已经被解散了


    GAME_STATUS_NO_START:"GAME_STATUS_NO_START",//游戏未开始
    GAME_STATUS_START:"GAME_STATUS_START",// 游戏已经开始了
    GAME_STATUS_ONE_OVER:"GAME_STATUS_ONE_OVER",//一局结束了
    GAME_STATUS_END:"GAME_STATUS_END",//结束了

    FENGPAILISTS:[1,9,11,19,21,29,31,32,33,34,35,36,37],
    BIGFENGLISTS:[35,36,37]
}



